config/routes.rb
NnteDebet::Application.routes.draw do
  get "courts" => "courts#index"

  resources :users
  resources :finances
  resources :dolgs
  resources :proplatis
  resources :ilists
  resources :delos do
    put :vsud, :on => :member
  end


  resources :agents
  resources :houses
  resources :dogovors
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
end

app/models/agent.rb
class Agent < ActiveRecord::Base
  attr_accessible :address, :e_mail, :name, :phonedogovor_number, :predsedatel, :predsedatel_phone, :buhgalter, :buhgalter_phone, :dogovor_number, :phone
  has_many :houses
  has_many :dogovors, dependent: :destroy
  has_many :dolgs, :through => :dogovors
  has_many :delos, :through => :dogovors
  has_many :proplatis

  validates :name, :presence => true, :uniqueness => true

 def self.search(search)
  if search
    where('name LIKE ?', "%#{search}%")
  else
    scoped
  end
 end

end

app/models/delo.rb
class Delo < ActiveRecord::Base
  attr_accessible :agent_id, :dolg_id, :finish, :dogovor_id, :isk_date, :sum, :status, :user_id

  belongs_to :dogovor

  has_many :ilists, dependent: :destroy


end

app/models/dogovor.rb
class Dogovor < ActiveRecord::Base
  attr_accessible :agent_id, :number, :date
  belongs_to :agent
  has_many :dolgs, dependent: :destroy
  has_many :proplatis, dependent: :destroy
  has_many :delos, dependent: :restrict
  has_many :ilists, :through => :delos

  validates :number, :presence => true
end

app/models/dolg.rb
class Dolg < ActiveRecord::Base
  attr_accessible :dogovor_id, :period, :sum, :month
  belongs_to :dogovor
  belongs_to :agent

  validates :sum, :numericality => true, :presence => true
  validates :dogovor_id, :presence => true, :uniqueness => { :scope => :month }
end

app/models/house.rb
class House < ActiveRecord::Base
  attr_accessible :agent_id, :number, :street
  belongs_to :agent

  validates :number, :street, :presence => true
end

app/models/ilist.rb
class Ilist < ActiveRecord::Base
  attr_accessible :agent_id, :date, :delo_id, :dolg_id, :finish, :number, :period, :pristav_id, :sum

  belongs_to :delo
end

app/models/obzvon.rb
class Obzvon < ActiveRecord::Base
  attr_accessible :agent_id, :answer, :phone_date, :repeat, :rezult
end

app/models/pristav.rb
class Pristav < ActiveRecord::Base
  attr_accessible :fio, :phone
end

app/models/proplati.rb
class Proplati < ActiveRecord::Base
  attr_accessible :date, :dogovor_id, :sum
  belongs_to :agent
  belongs_to :dogovor

  validates :date, :sum, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController

  def show
    @house = House.find(params[:id])
  end

  def index
    @houses = House.paginate(page: params[:page])
  #  @house = House.find(params[:id])
 #   @agent = house.agent
  end

  def new
    @house = House.new
  end

  def create
    @house = House.new(params[:house])
    if @house.save
      flash[:success] = "Welcome to the Sample App!"
      redirect_to houses_url
    else
      render 'new'
    end
  end

  def edit
  	@house = House.find(params[:id])
  end

  def update
  	@house = House.find(params[:id])
    if @house.update_attributes(params[:house])
      flash[:success] = "Profile updated"
      redirect_to houses_url
    else
      render 'edit'
    end
  end

  def destroy
    House.find(params[:id]).destroy
    flash[:success] = "Agent destroyed."
    redirect_to houses_url
  end

end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/courts_helper.rb
module CourtsHelper
end

app/helpers/delos_helper.rb
module DelosHelper
end

app/helpers/dogovors_helper.rb
module DogovorsHelper
end

app/helpers/dolgs_helper.rb
module DolgsHelper
end

app/helpers/finances_helper.rb
module FinancesHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/ilists_helper.rb
module IlistsHelper
end

app/helpers/obzvons_helper.rb
module ObzvonsHelper
end

app/helpers/pristavs_helper.rb
module PristavsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/houses/_house.html.erb
<tr>
<td>  <%= house.street %></td>
<td>  <%= house.number %></td>
<td>  <%= link_to house.agent.name, house.agent %></td>
  <% if current_user.admin? %>
<td>  

      <%= link_to '<i class=icon-trash></i>'.html_safe, house, method: :delete,
   								  :class => 'btn btn-mini',
                                  data: { confirm: "You sure?" } %>

      <%= link_to '<i class=icon-pencil></i>'.html_safe, edit_house_path(house), 
   								  :class => 'btn btn-mini' %>

</td>
  <% end %>
</tr>

app/views/houses/_menu.html.erb
  <aside class="span4">
    <section>

 			<ul class="nav nav-tabs nav-stacked">
        	 <li><%= link_to "Все дома", houses_path %></li>
        	 <li><%= link_to "Добавить дом", new_house_path %></li>
        	</ul>

    </section>

  </aside>

app/views/houses/edit.html.erb
<% provide(:title, "Edit agent") %>
<div class="row">
      <%= render './agents/menu' %>

 <h1>Update agent</h1>

  <div class="span8">

    <%= form_for(@house) do |f| %>
      <%= render 'shared/errorhouse_messages' %>

      <%= f.label :street, "Улица" %>
      <%= f.text_field :street %>

      <%= f.label :number, "Номер дома" %>
      <%= f.text_field :number %>

      <%= f.label :agent_id, "Организация" %>
      <%= f.text_field :agent_id %>

      <%= f.submit "Создать", class: "btn btn-large btn-primary" %>
    <% end %>

</div>
</div>

app/views/houses/index.html.erb
<% provide(:title, 'All users') %>
<div class="row">
      <%= render './agents/menu' %>
  <div class="span8">

	<%= will_paginate %>
		<table class="table table-bordered table-striped">
			<thead><tr><th>Улица</th><th>Номер дома</th><th>Организация</th>
				  <% if current_user.admin? %>
				<th>Действие</th>
				  <% end %>
			</tr></thead>
			<tdoby>
  			 <%= render @houses %>
			</tbody>
		</table>
	<%= will_paginate %> 

  </div>
</div>

app/views/houses/new.html.erb
<% provide(:title, 'Новый дом') %>
<div class="row">
      <%= render './agents/menu' %>

  <div class="span8">


    <%= form_for(@house) do |f| %>
      <%= render 'shared/errorhouse_messages' %>

      <%= f.label :street, "Улица" %>
      <%= f.text_field :street %>

      <%= f.label :number, "Номер дома" %>
      <%= f.text_field :number %>

      <%= f.label :agent_id, "Организация" %>
      <%= f.collection_select(:agent_id, Agent.all, :id, :name) %>

      <%= f.submit "Создать", class: "btn btn-large btn-primary" %>
    <% end %>



</div>
</div>