config/routes.rb
NnteDebet::Application.routes.draw do
  get "courts" => "courts#index"

  resources :users
  resources :finances
  resources :dolgs
  resources :proplatis
  resources :ilists
  resources :delos do
    put :vsud, :on => :member
  end


  resources :agents
  resources :houses
  resources :dogovors
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
end

app/models/agent.rb
class Agent < ActiveRecord::Base
  attr_accessible :address, :e_mail, :name, :phonedogovor_number, :predsedatel, :predsedatel_phone, :buhgalter, :buhgalter_phone, :dogovor_number, :phone
  has_many :houses
  has_many :dogovors, dependent: :destroy
  has_many :dolgs, :through => :dogovors
  has_many :delos, :through => :dogovors
  has_many :proplatis

  validates :name, :presence => true, :uniqueness => true

 def self.search(search)
  if search
    where('name LIKE ?', "%#{search}%")
  else
    scoped
  end
 end

end

app/models/delo.rb
class Delo < ActiveRecord::Base
  attr_accessible :agent_id, :dolg_id, :finish, :dogovor_id, :isk_date, :sum, :status, :user_id

  belongs_to :dogovor

  has_many :ilists, dependent: :destroy


end

app/models/dogovor.rb
class Dogovor < ActiveRecord::Base
  attr_accessible :agent_id, :number, :date
  belongs_to :agent
  has_many :dolgs, dependent: :destroy
  has_many :proplatis, dependent: :destroy
  has_many :delos, dependent: :restrict
  has_many :ilists, :through => :delos

  validates :number, :presence => true
end

app/models/dolg.rb
class Dolg < ActiveRecord::Base
  attr_accessible :dogovor_id, :period, :sum, :month
  belongs_to :dogovor
  belongs_to :agent

  validates :sum, :numericality => true, :presence => true
  validates :dogovor_id, :presence => true, :uniqueness => { :scope => :month }
end

app/models/house.rb
class House < ActiveRecord::Base
  attr_accessible :agent_id, :number, :street
  belongs_to :agent

  validates :number, :street, :presence => true
end

app/models/ilist.rb
class Ilist < ActiveRecord::Base
  attr_accessible :agent_id, :date, :delo_id, :dolg_id, :finish, :number, :period, :pristav_id, :sum

  belongs_to :delo
end

app/models/obzvon.rb
class Obzvon < ActiveRecord::Base
  attr_accessible :agent_id, :answer, :phone_date, :repeat, :rezult
end

app/models/pristav.rb
class Pristav < ActiveRecord::Base
  attr_accessible :fio, :phone
end

app/models/proplati.rb
class Proplati < ActiveRecord::Base
  attr_accessible :date, :dogovor_id, :sum
  belongs_to :agent
  belongs_to :dogovor

  validates :date, :sum, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/proplatis_controller.rb
class ProplatisController < ApplicationController

  def show
    @proplati = Proplati.find(params[:id])
  end

  def index
    @proplatis = Proplati.paginate(page: params[:page])

  end

  def new
    @proplati = Proplati.new
  end

  def create
    @proplati = Proplati.new(params[:proplati])
    if @proplati.save
      flash[:success] = "Welcome to the Sample App!"
      redirect_to finances_url
    else
      render 'new'
    end
  end

  def edit
  	@proplati = Proplati.find(params[:id])
  end

  def update
  	@proplati = Proplati.find(params[:id])
    if @proplati.update_attributes(params[:proplati])
      flash[:success] = "Profile updated"
      redirect_to proplatis_url
    else
      render 'edit'
    end
  end

  def destroy
    Proplati.find(params[:id]).destroy
    flash[:success] = "Agent destroyed."
    redirect_to proplatis_url
  end

end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/courts_helper.rb
module CourtsHelper
end

app/helpers/delos_helper.rb
module DelosHelper
end

app/helpers/dogovors_helper.rb
module DogovorsHelper
end

app/helpers/dolgs_helper.rb
module DolgsHelper
end

app/helpers/finances_helper.rb
module FinancesHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/ilists_helper.rb
module IlistsHelper
end

app/helpers/obzvons_helper.rb
module ObzvonsHelper
end

app/helpers/pristavs_helper.rb
module PristavsHelper
end

app/helpers/proplatis_helper.rb
module ProplatisHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/proplatis/_dogovor.html.erb
<tr>
<td>  <%= dogovor.number %></td>
<td>  <%= link_to dogovor.agent.name, dogovor.agent %></td>
  <% if current_user.admin? %>
<td>  

      <%= link_to '<i class=icon-trash></i>'.html_safe, dogovor, method: :delete,
   								  :class => 'btn btn-mini',
                                  data: { confirm: "You sure?" } %>

      <%= link_to '<i class=icon-pencil></i>'.html_safe, edit_dogovor_path(dogovor), 
   								  :class => 'btn btn-mini' %>

</td>
  <% end %>
</tr>

app/views/proplatis/_menu.html.erb
  <aside class="span4">
    <section>

 			<ul class="nav nav-tabs nav-stacked">
        	 <li><%= link_to "Все договора", dogovors_path %></li>
        	 <li><%= link_to "Добавить договор", new_dogovor_path %></li>
        	</ul>

    </section>

  </aside>

app/views/proplatis/_proplati.html.erb
<tr>

<td>  <%= proplati.dogovor.number %></td>
<td>  <%= number_to_currency(proplati.sum, :unit => "руб.", :separator => ",", :delimiter => " ", :format => "%n %u") %></td>
<td>  <%= proplati.date %><br>
</td>
  <% if current_user.admin? %>
<td> 



      <%= link_to '<i class=icon-trash></i>'.html_safe, proplati, method: :delete,
   								  :class => 'btn btn-mini',
                                  data: { confirm: "You sure?" } %>

      <%= link_to '<i class=icon-pencil></i>'.html_safe, edit_proplati_path(proplati), 
   								  :class => 'btn btn-mini' %>

</td>
  <% end %>
</tr>

app/views/proplatis/edit.html.erb
<% provide(:title, "Edit agent") %>
<div class="row">
      <%= render './finances/menu' %>

 <h1>Update agent</h1>

  <div class="span8">

    <%= form_for(@proplati) do |f| %>
      <%= render 'shared/errorproplati_messages' %>

      <%= f.label :sum, "Оплаченная сумма" %>
      <%= f.text_field :sum %>

      <%= f.label :date, "Дата оплаты" %>
      <%= f.date_select :date %>

      <%= f.label :dogovor_id, "Организация" %>
      <%= f.collection_select(:dogovor_id, Dogovor.all, :id, :number) %>

      <%= f.submit "Создать", class: "btn btn-large btn-primary" %>
    <% end %>

</div>
</div>

app/views/proplatis/index.html.erb
<% provide(:title, 'Все договора') %>
<div class="row">
      <%= render './finances/menu' %>
  <div class="span8">

	<%= will_paginate %>
		<table class="table table-bordered table-striped">
			<thead><tr><th>Номер договора</th><th>Сумма</th><th>Дата оплаты</th>
				  <% if current_user.admin? %>
				<th>Действие</th>
				  <% end %>
			</tr></thead>
			<tdoby>
  			 <%= render @proplatis %>
			</tbody>
		</table>
	<%= will_paginate %> 

  </div>
</div>

app/views/proplatis/new.html.erb
<% provide(:title, 'Новый договор') %>
<div class="row">
      <%= render './finances/menu' %>

  <div class="span8">


    <%= form_for(@proplati) do |f| %>
      <%= render 'shared/errorproplati_messages' %>

      <%= f.label :sum, "Оплаченная сумма" %>
      <%= f.text_field :sum %>

      <%= f.label :date, "Дата оплаты" %>
      <%= f.date_select :date %>

      <%= f.label :dogovor_id, "Номер договора" %>
      <%= f.collection_select(:dogovor_id, Dogovor.all, :id, :number) %>

      <%= f.submit "Создать", class: "btn btn-large btn-primary" %>
    <% end %>




</div>
</div>

app/views/proplatis/show.html.erb
<% provide(:title, @agent.name) %>
<div class="row">

  <aside class="span4">
    <section>

 			<ul class="nav nav-tabs nav-stacked">
        	 <li><%= link_to "Все организации", agents_path %></li>
        	 <li><%= link_to "Добавить организацию", new_agent_path %></li>
        	</ul>

    </section>


<%= link_to 'Изменить', edit_agent_path(@agent), 
   								  :class => 'btn btn-primary btn-warning' %>

<%= link_to 'удалить', @agent, method: :delete,
   								  :class => 'btn btn-primary btn-danger',
                                  data: { confirm: "You sure?" } %>

  </aside>


 <div class="span8">
      <h1> <%= @house.name %> </h1>

<strong>Координаты:</strong>
	<div class="well well-small">
	 <strong>Адрес:</strong>
	 	<% if @agent.address? %>
	 	<%= @agent.address %> 
		 <% else %>
	 	нет
	 	<% end %>
	 <strong>Телефон:</strong> <%= @agent.phone %>
	 <strong>E-mail:</strong> <%= @agent.e_mail %>
	</div>



 </div>
</div>