config/routes.rb
NnteDebet::Application.routes.draw do
  get "courts" => "courts#index"

  resources :users
  resources :finances
  resources :dolgs
  resources :proplatis
  resources :ilists
  resources :delos do
    put :vsud, :on => :member
  end


  resources :agents
  resources :houses
  resources :dogovors
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
end

app/models/agent.rb
class Agent < ActiveRecord::Base
  attr_accessible :address, :e_mail, :name, :phonedogovor_number, :predsedatel, :predsedatel_phone, :buhgalter, :buhgalter_phone, :dogovor_number, :phone
  has_many :houses
  has_many :dogovors, dependent: :destroy
  has_many :dolgs, :through => :dogovors
  has_many :delos, :through => :dogovors
  has_many :proplatis

  validates :name, :presence => true, :uniqueness => true

 def self.search(search)
  if search
    where('name LIKE ?', "%#{search}%")
  else
    scoped
  end
 end

end

app/models/delo.rb
class Delo < ActiveRecord::Base
  attr_accessible :agent_id, :dolg_id, :finish, :dogovor_id, :isk_date, :sum, :status, :user_id

  belongs_to :dogovor

  has_many :ilists, dependent: :destroy


end

app/models/dogovor.rb
class Dogovor < ActiveRecord::Base
  attr_accessible :agent_id, :number, :date
  belongs_to :agent
  has_many :dolgs, dependent: :destroy
  has_many :proplatis, dependent: :destroy
  has_many :delos, dependent: :restrict
  has_many :ilists, :through => :delos

  validates :number, :presence => true
end

app/models/dolg.rb
class Dolg < ActiveRecord::Base
  attr_accessible :dogovor_id, :period, :sum, :month
  belongs_to :dogovor
  belongs_to :agent

  validates :sum, :numericality => true, :presence => true
  validates :dogovor_id, :presence => true, :uniqueness => { :scope => :month }
end

app/models/house.rb
class House < ActiveRecord::Base
  attr_accessible :agent_id, :number, :street
  belongs_to :agent

  validates :number, :street, :presence => true
end

app/models/ilist.rb
class Ilist < ActiveRecord::Base
  attr_accessible :agent_id, :date, :delo_id, :dolg_id, :finish, :number, :period, :pristav_id, :sum

  belongs_to :delo
end

app/models/obzvon.rb
class Obzvon < ActiveRecord::Base
  attr_accessible :agent_id, :answer, :phone_date, :repeat, :rezult
end

app/models/pristav.rb
class Pristav < ActiveRecord::Base
  attr_accessible :fio, :phone
end

app/models/proplati.rb
class Proplati < ActiveRecord::Base
  attr_accessible :date, :dogovor_id, :sum
  belongs_to :agent
  belongs_to :dogovor

  validates :date, :sum, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/delos_controller.rb
class DelosController < ApplicationController

  def show
    @delo = Delo.find(params[:id])
  end

  def index
    @delos = Delo.order("created_at").paginate(page: params[:page])
  end

  def status
    @delo = Delo.find(params[:id])
    @delo.status = 0
    @delo.save
    redirect_to delos_url
  end

  def vsud
    @delo = Delo.find(params[:id])
    @delo.toggle!(:vsude)
    redirect_to delos_url
  end

  def new
    @delo = Delo.new
  end

  def create
    @delo = Delo.new(params[:delo])
    if @delo.save
      flash[:success] = "Welcome to the Sample App!"
      redirect_to delos_url
    else
      render 'new'
    end
  end

  def edit
  	@delo = Delo.find(params[:id])
  end

  def update
  	@delo = Delo.find(params[:id])
    if @delo.update_attributes(params[:delo])
      flash[:success] = "Profile updated"
      redirect_to delos_url
    else
      render 'edit'
    end
  end

  def destroy
    Delo.find(params[:id]).destroy
    flash[:success] = "Dolg destroyed."
    redirect_to delos_url
  end

end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/courts_helper.rb
module CourtsHelper
end

app/helpers/delos_helper.rb
module DelosHelper
end

app/helpers/dogovors_helper.rb
module DogovorsHelper
end

app/helpers/dolgs_helper.rb
module DolgsHelper
end

app/helpers/finances_helper.rb
module FinancesHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/ilists_helper.rb
module IlistsHelper
end

app/helpers/obzvons_helper.rb
module ObzvonsHelper
end

app/helpers/pristavs_helper.rb
module PristavsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def current_user?(user)
    user == current_user
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/delos/_delo.html.erb
<tr>
<td>  <%= delo.dogovor.number %></td>
<td>  <%= link_to delo.dogovor.agent.name, delo.dogovor.agent %> </td>
<td>  <%= Russian::strftime(delo.created_at, "%B") %></td>
<td>  <%= number_to_currency(delo.sum, :unit => "руб.", :separator => ",", :delimiter => " ", :format => "%n %u") %></td>
<td>  

	<% if delo.vsude %>
		<%= link_to "Да", vsud_delo_url(delo), method: :put %>
	<% else %>
		<%= link_to "Нет", vsud_delo_url(delo), method: :put %>
	<% end %>
</td>

<td>   <%= delo.id %><%= link_to delo.status, vsud_delo_path(delo), data: { toggle: "modal", target: "#modelstatus" } %>

  <% if delo.status = 0 %>
<%= print "HI" %>
<% end %>

  <% if delo.status == 1 %>
<%= print "HI" %>
<% end %>

      <%= render './shared/status' %>

<%= form_for @delo, :as => :delo, :url => delo_path(delo), :method => "put" do |f| %>

 <%= f.select(:status, options_for_select([['Создан', 0], ['Отправлен в суд', 1], ['Принято к рассмотрению', 2], ['Заседание состоялось', 3], ['Получено решение суда', 4], ['Подана аппеляция', 5], ['Получен исполнительный лист', 6]]), :prompt => "Обновить статус") %>

      <%= f.submit "Создать", class: "btn btn-primary" %>
       <% end %>


      <%= render './shared/modelstatus' %>
</td>
  <% if current_user.admin? %>
<td>  

      <%= link_to '<i class=icon-trash></i>'.html_safe, delo, method: :delete,
   								  :class => 'btn btn-mini',
                                  data: { confirm: "You sure?" } %>

      <%= link_to '<i class=icon-pencil></i>'.html_safe, edit_delo_path(delo), 
   								  :class => 'btn btn-mini' %>

</td>
  <% end %>
</tr>

app/views/delos/index.html.erb
<% provide(:title, 'Все дела в суде') %>
<div class="row">
      <%= render './courts/menu' %>
  <div class="span8">

	<%= will_paginate %>
		<table class="table table-bordered table-striped">
			<thead><tr><th>По договору №</th><th>Организация</th><th>Дата подачи иска</th><th>Сумма иска</th><th>Дело возбуждено</th><th>Дата судебного заседания</th>
				  <% if current_user.admin? %>
				<th>Действие</th>
				  <% end %>
			</tr></thead>
			<tdoby>
  			 <%= render @delos %>
			</tbody>
		</table>
	<%= will_paginate %> 


      <%= render './shared/modelstatus' %>


  </div>
</div>

app/views/delos/new.html.erb
<% provide(:title, 'Новый договор') %>
<div class="row">
      <%= render './courts/menu' %>
  <div class="span8">

    <%= form_for(@delo) do |f| %>


      <%= f.label :sum, "Сумма иска" %>
      <%= f.text_field :sum %>

      <%= f.label :status, "Статус дела" %>
      <%= f.select(:status, options_for_select([['Создан', 0], ['Отправлен в суд', 1], ['Принято к рассмотрению', 2], ['Заседание состоялось', 3], ['Получено решение суда', 4], ['Подана аппеляция', 5], ['Получен исполнительный лист', 6]])) %>

      <%= f.label :isk_date, "Дата подачи иска" %>
      <%= f.date_select :isk_date %>

      <%= f.label :dogovor_id, "Номер договора" %>
      <%= f.collection_select(:dogovor_id, Dogovor.all, :id, :number) %>

      <%= f.submit "Создать", class: "btn btn-large btn-primary" %>
    <% end %>



</div>
</div>